# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

run-name: CI/CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  schedule:
  - cron: "0 3 * * *"
    
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2


    # Install Python and pip
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
         python-version: '3.7'

   #Install dependecies andrun stitch_job.py
    - name: Run stitch_job.py
      run: |
         python -m pip install --upgrade pip
         pip install requests
         python .github/workflows/stitch_job.py
       
    - name: Run dbt.py
      run: |
         python .github/workflows/dbt.py         
       
    - name: Run power_bi.py
      run: |
         pip install msal
         python .github/workflows/power_bi.py
